trigger:
- master

pool:
    vmImage: 'vs2017-win2016'

variables:
    solution: 'WebGoat/'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'
    enableCustomProcessTemplate: true
    customWorkItemType: 'Bug'
    customPTActiveStatus: 'In Progress'
    customPTNewStatus: 'New'
    customPTResolvedStatus: 'Resolved'
    customPTCloseStatus: 'Closed'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
   packageType: 'sdk'
   version:

- task: DotNetCoreCLI@2
  inputs:
   command: 'build'
   projects: 'D:\a\1\s\WebGoat'

