# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseNode@1
  inputs:
    versionSpec: $(node_version)
    
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'
    clean: true
    restoreNugetPackages: true
    createLogFile: true


- task: Snyk@2
  inputs:
    multiFile: true
    files: |
      #yarn.lock
      #package.json
      #package-lock.json
      #Gemfile
      #Gemfile.lock
      #pom.xml
      #Pipfile
      #requirements.txt
      #build.gradle
      #build.gradle.kts
      #build.sbt
      #Gopkg.lock
      #**/vendor/vendor.json
      #**/obj/project.assets.json
      #packages.config
      #composer.lock
      
      #!**/node_modules/**/*
    protect: false
    test: true
    monitor: false
    authType: 'endpoint'
    endpoint: 'AzurePipeline-Snyk Token'
    severityThreshold: 'default'
    failBuild: false
    dev: true
    trustPolicies: false