name: $(Date:yyyy.MM.dd).$(Rev:r)
variables:
  SNYK_TOKEN: 3e74cf14-a819-4424-9652-aee1fb06348b
jobs:
- job:
  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - task: NuGetToolInstaller@1
    displayName: 'Installing Nuget'
    inputs:
      versionSpec: 
      checkLatest: true

  - task: NuGetCommand@2
    displayName: 'Installing Microsoft.CodeAnalysis.FxCopAnalyzer'
    inputs:
      command: 'custom'
      arguments: 'install Microsoft.CodeAnalysis.FxCopAnalyzers -Version 2.6.3 -OutputDirectory D:\a\1\s\WebGoat.NET\packages'

  - task: NuGetCommand@2
    displayName: 'Security Code Scan - static code analyzer for .NET'
    inputs:
      command: 'custom'
      arguments: 'install SecurityCodeScan -Version 3.3.0 -OutputDirectory D:\a\1\s\WebGoat.NET\packages'


  - task: NuGetCommand@2
    displayName: 'Restoring Nuget Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'


  - task: VSBuild@1
    displayName: 'Visual Studio Build'
    inputs:
     solution: '**/*.sln'
     vsVersion: '15.0'
     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true  /p:PackageLocation="$(build.artifactStagingDirectory)"  /p:RunCodeAnalysis=true'
     platform: '$(buildPlatform)'
     configuration: '$(buildConfiguration)'


